version: 2

project_name: rsecure

builds:
  - id: rsecure
    builder: rust
    binary: rsecure
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

archives:
  - id: rsecure
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

nfpms:
  - id: rsecure
    package_name: rsecure
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    homepage: https://github.com/containerscrew/rsecure
    vendor: containerscrew
    description: Secure file encryption using pure Rust and AES
    maintainer: containerscrew <info@containerscrew.com>
    license: GPL3
    formats:
      - apk
      - deb
      - rpm
      - archlinux

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg2
    output: true
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

snapshot:
  version_template: "{{ .Tag }}"

release:
  draft: false

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: rsecure
    binaries:
      - rsecure
    url:
      template: "https://github.com/containerscrew/rsecure/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/containerscrew/rsecure/"
    homepage: "https://github.com/containerscrew/rsecure"
    description: "Secure file encryption using pure Rust and AES"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    repository:
      owner: containerscrew
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

aur_sources:
  - name: rsecure
    homepage: "https://github.com/containerscrew/rsecure"
    description: "Secure file encryption CLI written in Rust"
    maintainers:
      - "containerscrew <info@containerscrew.com>"
    license: "GPL3"

    git_url: "ssh://aur@aur.archlinux.org/rsecure.git"
    private_key: "{{ .Env.AUR_KEY }}"

    depends: []
    makedepends:
      - rust
      - cargo

    build: |-
      cd "$pkgname-$pkgver"
      cargo build --release --locked

    package: |-
      cd "$pkgname-$pkgver"
      install -Dm755 "target/release/rsecure" "$pkgdir/usr/bin/rsecure"
      install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
      install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"

    commit_msg_template: "Update to {{ .Tag }}"

aurs:
  - name: rsecure-bin
    ids:
      - rsecure

    homepage: "https://github.com/containerscrew/rsecure"
    description: "Secure file encryption CLI written in Rust (pre-compiled binary)"
    maintainers:
      - "containerscrew <info@containerscrew.com>"
    license: "GPL3"

    git_url: "ssh://aur@aur.archlinux.org/rsecure-bin.git"
    private_key: "{{ .Env.AUR_KEY }}"

    provides:
      - rsecure
    conflicts:
      - rsecure

    package: |-
      install -Dm755 "rsecure" "$pkgdir/usr/bin/rsecure"
      install -Dm644 "README.md" "$pkgdir/usr/share/doc/rsecure/README.md"
      install -Dm644 "LICENSE" "$pkgdir/usr/share/licenses/rsecure/LICENSE"

    commit_msg_template: "Update rsecure-bin to {{ .Tag }}"
