# This file was generated by GoReleaser. DO NOT EDIT.
cask "rsecure" do
  name "rsecure"
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rsecure"

  on_macos do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_amd64.zip",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "f157b765922a0cb86159bd68dbb962cf33264413e93cc5715f7f1926bf4aa5ff"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_arm64.zip",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "67a2fa663010c331a149cf824cdda7d7a0e23463ed11ca74ef76aedbe632c9cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_amd64.zip",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "4827d7f5f04bdef646fa3e96f67b6463732426cb1565dfa09d15a9fe659cf120"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_arm64.zip",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "1d36a7fe8504f226eac6cc5b3d90d6e4b4d46c10cc4175a53560d5906950e282"
    end
  end

  # No zap stanza required
end
