name: Release

permissions:
  contents: write
  pull-requests: write
  discussions: write

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.89.0

jobs:
  publish-crate:
    name: Publish crate to creates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup update
          rustup default ${{ env.RUST_VERSION }}
      - name: Publish to creates.io (dry-run)
        run: |
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cargo publish
